Repository bozhenaboichuk/Lunch, pull requests merged in 2022-02, with the labels that each got.

#33 Feature reset password
  Gemfile
  Gemfile.lock
  app/views/users/shared/_links.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
Labels: enhancement

#32 fixed align for flash message
  app/assets/stylesheets/application.css
  app/views/layouts/application.html.haml
  app/views/layouts/devise.html.haml
Labels: bug, ui

#35 Add tailwind via gem, remove obsolete files
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application.tailwind.css
  app/assets/stylesheets/wind.css
  app/views/layouts/application.html.haml
  app/views/layouts/devise.html.haml
  bin/dev
  config/tailwind.config.js
  tailwind.config.js
Labels: bug, invalid

#44 41 enchance orders view
  Gemfile
  Gemfile.lock
  app/controllers/orders_controller.rb
  app/models/order.rb
  app/views/orders/index.html.haml
Labels: enhancement

#39 Feature rspec
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/imagekitio.rb
  spec/models/restaurant_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement
